### ISSUE TITLE
Don't display MDC fields

### ISSUE THREAD

**Issue by joaopalma5** [kifj/camunda-wildfly-logging#1]
Hello

I have installed this plugin and wildfly-logstash but my result its just that(app status):

`"{"@timestamp":"2019-12-09T11:17:59.412+0000","@message":"RESTEASY002205: Adding provider class org.camunda.bpm.engine.rest.exception.JsonParseExceptionHandler from Application class org.camunda.bpm.webapp.{"@timestamp":"2019-12-09T11:17:59.414+0000","@message":"RESTEASY002205: Adding provider class org.camunda.bpm.engine.rest.hal.JacksonHalJsonProvider from Application class org.camunda.bpm.webapp.impl.engi{"@timestamp":"2019-12-09T11:17:59.443+0000","@message":"RESTEASY002225: Deploying javax.ws.rs.core.Application: class org.camunda.bpm.admin.impl.web.AdminApplication","@source":"org.jboss.resteasy.resteas{"@timestamp":"2019-12-09T11:17:59.474+0000","@message":"RESTEASY002205: Adding provider class org.camunda.bpm.engine.rest.mapper.JacksonConfigurator from Application class org.camunda.bpm.admin.impl.web.A{"@timestamp":"2019-12-09T11:17:59.486+0000","@message":"RESTEASY002200: Adding class resource org.camunda.bpm.admin.impl.plugin.resources.AdminPluginsRootResource from Application class org.camunda.bpm.ad{"@timestamp":"2019-12-09T11:17:59.495+0000","@message":"RESTEASY002205: Adding provider class com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider from Application class org.camunda.bpm.admin.impl.web.Adm{"@timestamp":"2019-12-09T11:17:59.503+0000","@message":"RESTEASY002205: Adding provider class org.camunda.bpm.engine.rest.exception.RestExceptionHandler from Application class org.camunda.bpm.admin.impl.w{"@timestamp":"2019-12-09T11:17:59.520+0000","@message":"RESTEASY002200: Adding class resource org.camunda.bpm.webapp.impl.security.auth.UserAuthenticationResource from Application class org.camunda.bpm.ad{"@timestamp":"2019-12-09T11:17:59.530+0000","@message":"RESTEASY002205: Adding provider class org.camunda.bpm.engine.rest.exception.ExceptionHandler from Application class org.camunda.bpm.admin.impl.web.A{"@timestamp":"2019-12-09T11:17:59.534+0000","@message":"RESTEASY002200: Adding class resource org.camunda.bpm.admin.impl.web.SetupResource from Application class org.camunda.bpm.admin.impl.web.AdminApplic{"@timestamp":"2019-12-09T11:18:08.403+0000","@message":"RESTEASY002225: Deploying javax.ws.rs.core.Application: class org.camunda.bpm.tasklist.impl.web.TasklistApplication","@source":"org.jboss.resteasy.r{"@timestamp":"2019-12-09T11:18:08.406+0000","@message":"RESTEASY002205: Adding provider class org.camunda.bpm.engine.rest.mapper.JacksonConfigurator from Application class org.camunda.bpm.tasklist.impl.we{"@timestamp":"2019-12-09T11:18:08.409+0000","@message":"RESTEASY002200: Adding class resource org.camunda.bpm.tasklist.impl.plugin.resources.TasklistPluginsRootResource from Application class org.camunda."`

How can I enable the MDC fields?

**Comment by kifj** [comment]
Sorry for the late reply, I didn't notice your request.

In the lines above I can not see any logging which refers to some log messages you are producing within a service task. There is nothing more to enable, but you need to write some log lines.

For example like this

```
public class MyTask implements JavaDelegate {
  private static final Logger LOG = LoggerFactory.getLogger(MyTask.class);
 
 @Override
  public void execute(DelegateExecution execution) throws JMSException {
    LOG.info("this is my task: {}", execution);
  }
}
```
